import { FilterOption, SizeOption, SortOption } from "../types/filters";

export const SORT_OPTIONS = [
  { value: SortOption.RECOMMENDED, label: "Recommended" },
  { value: SortOption.WHATS_NEW, label: "What's New" },
  { value: SortOption.POPULARITY, label: "Popularity" },
  { value: SortOption.BETTER_DISCOUNT, label: "Better Discount" },
  { value: SortOption.PRICE_HIGH_TO_LOW, label: "Price: High to Low" },
  { value: SortOption.PRICE_LOW_TO_HIGH, label: "Price: Low to High" },
  { value: SortOption.CUSTOMER_RATING, label: "Customer Rating" },
];

export const CATEGORY_OPTIONS: FilterOption[] = [
  { id: "kurta-sets", label: "Kurta Sets", count: 412959 },
  { id: "kurtas", label: "Kurtas", count: 166227 },
];

export const BRAND_OPTIONS: FilterOption[] = [
  { id: "7threads", label: "7Threads", count: 41234 },
  { id: "kalini", label: "KALINI", count: 62821 },
  { id: "here-now", label: "HERE&NOW", count: 78447 },
  { id: "ethnic-basket", label: "Ethnic Basket", count: 138162 },
  { id: "poomantara", label: "poomantara", count: 10268 },
  { id: "anouk", label: "Anouk", count: 14014 },
  { id: "moda-rapido", label: "Moda Rapido", count: 19431 },
  { id: "sangria", label: "Sangria", count: 19346 },
];

export const COLOR_OPTIONS: FilterOption[] = [
  { id: "red", label: "Red" },
  { id: "blue", label: "Blue" },
  { id: "green", label: "Green" },
  { id: "yellow", label: "Yellow" },
  { id: "pink", label: "Pink" },
  { id: "black", label: "Black" },
  { id: "white", label: "White" },
  { id: "orange", label: "Orange" },
  { id: "purple", label: "Purple" },
  { id: "brown", label: "Brown" },
  { id: "grey", label: "Grey" },
  { id: "beige", label: "Beige" },
];

export const SIZE_OPTIONS: SizeOption[] = [
  { id: "3xs", label: "3XS" },
  { id: "xxs", label: "XXS" },
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "XXL" },
  { id: "3xl", label: "3XL" },
  { id: "4xl", label: "4XL" },
  { id: "5xl", label: "5XL" },
  { id: "6xl", label: "6XL" },
  { id: "lxl", label: "L/XL" },
  { id: "xlxxl", label: "XL/XXL" },
  { id: "mxl", label: "M/XL" },
  { id: "7xl", label: "7XL" },
  { id: "8xl", label: "8XL" },
  { id: "9xl", label: "9XL" },
  { id: "10xl", label: "10XL" },
  { id: "11xl", label: "11XL" },
  { id: "12xl", label: "12XL" },
  { id: "13-15y", label: "13-15Y" },
  { id: "14-15y", label: "14-15Y" },
  { id: "4-6y", label: "4-6Y" },
  { id: "6-7y", label: "6-7Y" },
  { id: "8-9y", label: "8-9Y" },
  { id: "9-10y", label: "9-10Y" },
  { id: "10-11y", label: "10-11Y" },
  { id: "11-12y", label: "11-12Y" },
  { id: "12-13y", label: "12-13Y" },
  { id: "27", label: "27" },
  { id: "28", label: "28" },
  { id: "29", label: "29" },
  { id: "30", label: "30" },
  { id: "31", label: "31" },
  { id: "32", label: "32" },
  { id: "33", label: "33" },
  { id: "34", label: "34" },
  { id: "35", label: "35" },
  { id: "36", label: "36" },
  { id: "38", label: "38" },
  { id: "40", label: "40" },
  { id: "42", label: "42" },
  { id: "44", label: "44" },
  { id: "46", label: "46" },
  { id: "48", label: "48" },
  { id: "50", label: "50" },
  { id: "51", label: "51" },
  { id: "32-55", label: "32/55" },
  { id: "34-55", label: "34/55" },
  { id: "36-57", label: "36/57" },
  { id: "38-60", label: "38/60" },
  { id: "40-63", label: "40/63" },
  { id: "42-66", label: "42/66" },
  { id: "44-69", label: "44/69" },
  { id: "32-42", label: "32-42" },
  { id: "34-43", label: "34-43" },
  { id: "36-45", label: "36-45" },
  { id: "38-47", label: "38-47" },
  { id: "40-49", label: "40-49" },
  { id: "42-51", label: "42-51" },
  { id: "44-52", label: "44-52" },
  { id: "customise", label: "Customise" },
];

export const BUNDLE_OPTIONS: FilterOption[] = [
  { id: "3xs", label: "3XS" },
  { id: "xxs", label: "XXS" },
  { id: "xs", label: "XS" },
  { id: "s", label: "S" },
  { id: "m", label: "M" },
  { id: "l", label: "L" },
  { id: "xl", label: "XL" },
  { id: "xxl", label: "XXL" },
  { id: "3xl", label: "3XL" },
  { id: "4xl", label: "4XL" },
  { id: "5xl", label: "5XL" },
  { id: "6xl", label: "6XL" },
];

export const COUNTRY_OPTIONS: FilterOption[] = [
  { id: "all", label: "All Countries" },
  { id: "india", label: "India" },
];

export const DEFAULT_PRICE_RANGE = {
  min: 0,
  max: 10000,
};
